kind: Pod
apiVersion: v1
metadata:
  name: environments
  annotations: 
    description: "Testing env var inside the K8's "
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
      env:                        # List of environment variables to be used inside the pod
        - name: NAME
          value: HEISENBERG

