kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myrs
spec:
  replicas: 2
  selector:
    matchExpressions:  # These must match the labels
      - key: myname
        operator: In
        values: [Suraj, SurajDev, SurajCoder]  # Because Suraj has many talents!
      - key: env
        operator: NotIn
        values: [production]  # No production, we're just having fun here!
  template:
    metadata:
      name: testpod7
      labels:
        myname: Suraj  # Let's stick with Suraj for now
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo 'Code karo, masti karo, Kubernetes seekho!'; sleep 5 ; done"]  # Fun message!
