kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    myname: Suraj  # Label selector updated to match the new name
  template:
    metadata:
      name: testpod6
      labels:
        myname: Suraj  # Label updated to match the selector
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello-Suraj; sleep 5 ; done"]
